### ISSUE TITLE
how to get the dataset FlowNet2_checkpoint.pth.tar

### ISSUE THREAD

**Issue by ww-dut** [AniruthSuresh/Real-Time-Visual-Servoing-Grasping#1]
Hello! When i run the grasp demo, i get a error  --No such file or directory: '../data/FlowNet2_checkpoint.pth.tar'. How can i get the dataset FlowNet2_checkpoint.pth.tar?Thankyou very much.

**Comment by AniruthSuresh** [comment]
Hi ! 
So since the checkpoint is too big to load in git , I couldn't push it in . But u can always train your own checkpoint by navigating to 
```src/controllers/rtvs/flownet2-pytorch``` and running the main.py file to generate the checkpoint. 

Thanks
